### ISSUE TITLE
Minor fix required in documentation 😅

### ISSUE THREAD

**Issue by SuperThinking** [createnl/grouped-checkboxes#10]
First of all, great work!
But can you just change a small thing in the documentation that it's 
`import {
  AllCheckerCheckbox,
  Checkbox,
  CheckboxGroup
} from "@createnl/grouped-checkboxes";`

and not just `from "grouped-checkboxes"`

Or just merge it #11 😅

**Comment by AlexLisenkov** [comment]
Fixes #11
