### ISSUE TITLE
Nested CheckboxGroup

### ISSUE THREAD

**Issue by ahmedali5530** [createnl/grouped-checkboxes#21]
Hi, can we use multiple CheckboxGroup inside the parent CheckboxGroup. 
Like for example i have a table and i want to toggle each row with a Master checkbox and then i need another to toggle all checkboxes in table.
Is this possible.
I tried but only the inner ones (AllCheckerCheckbox) work. And master does not.

**Comment by AlexLisenkov** [comment]
This is not possible at the moment.
