### ISSUE TITLE
Logging dynamic ID's to console

### ISSUE THREAD

**Issue by Modulo216** [createnl/grouped-checkboxes#8]
I upgraded to 1.1.0 and I notice the dynamic ID's get logged to the console.  Was this intended?  Is there a way to disable this?  It looks like it comes from CheckboxGroup.tsx line 103.
![output](https://user-images.githubusercontent.com/7266062/72559224-50b9c300-3872-11ea-9974-3dd1ee89e625.PNG)

**Comment by AlexLisenkov** [comment]
This was not intentional, thank you for letting me know. 
You can update to version 1.1.1.
